language: python
python:
  - 2.7

git:
  submodules: false

before_install:
  # - git submodule init
  # - git submodule update --depth=22

install:
  - pip install -r requirements.txt

script:
  # - flake8
  - ./scripts/xgettext.sh
  - make
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ]; then
      make zip
    fi

# deploy:
#   provider: releases
#   api_key: $GH_TOKEN
#   file:
#     - script.elementum.burst-${TRAVIS_TAG:1}.zip
#   skip_cleanup: true
#   overwrite: true
#   on:
#     tags: true
